##### WEATHER #####
- platform: generic
  still_image_url: https://radar.weather.gov/Conus/Loop/northeast_loop.gif
  name: "Northeast Radar"
- platform: generic
  still_image_url: https://radar.weather.gov/Conus/Loop/NatLoop.gif
  name: "U.S. Radar"
- platform: generic
  still_image_url: https://radar.weather.gov/ridge/lite/NCR/DOX_loop.gif
  name: "Delaware Radar"
#### CAMERA ####
- platform: mjpeg
  mjpeg_url: http://192.168.0.216:8081/video.mjpg
  name: MOD-T
