homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 106
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml

# Enables the frontend
frontend:

device_tracker:
  - platform: netgear
    username: !secret netgear_username
    password: !secret netgear_password
    port: 5000
    track_new_devices: no
    interval_seconds: 60
    consider_home: 180

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret hass_url 

# Checks for available updates
updater:

recorder:
  purge_days: 60
  db_url: mysql://127.0.0.1/hass
  exclude:
    domains:
      - automation
      - updater
      - group
      - script
    entities:
      - sensor.average_load_15m
      - sensor.received_eth0
      - sensor.sent_eth0
      - sensor.since_last_boot
      - sun.sun
      - camera.delaware_radar
      - camera.northeast_radar
      - camera.us_radar


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sun.sun
      - sensor.pws_wind_dir
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary

logger:
  default: warn

# Track the sun
sun:

# Text to speech
tts:
  platform: google
  cache: false
  #cache: true
  #cache_dir: /tmp/tts
  time_memory: 300

ifttt:
  key: !secret ifttt_api_key
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

usps:
  username: !secret usps_username
  password: !secret usps_password

wemo:
  static:
    - !secret wemo_ip

sensor: !include_dir_merge_list sensors

automation: !include_dir_merge_list automations

group: !include  groups.yaml

script: !include_dir_merge_named scripts

camera: !include cameras.yaml

notify: !include notifiers.yaml

media_player: !include media_players.yaml
