#- platform: usps
#  username: !secret usps_username
#  password: !secret usps_password
- platform: ups
  username: !secret ups_username
  password: !secret ups_password
- platform: fedex
  username: !secret fedex_username
  password: !secret fedex_password
- platform: template
  sensors:
    ups_delivered:
      friendly_name: 'UPS'
      value_template: >
                     {% if states.sensor.ups.attributes.out_for_delivery is defined %}
                       {{ states.sensor.ups.attributes.out_for_delivery }}
                     {% elif states.sensor.ups.attributes.delivered is defined %}
                       {{ states.sensor.ups.attributes.delivered }}
                     {% else %}
                        0
                     {% endif %}
                     #- platform: template
                     #sensors:
                     #usps_delivered:
                     #friendly_name: 'USPS'
                     #value_template: >
                     #{% if states.sensor.usps_packages.attributes.delivered is not defined %}
                     #   0
                     #{% else %}
                     #  {{ states.sensor.usps_packages.attributes.delivered }}
                     #{% endif %}
