- platform: template
  sensors:
    media_players_active:
      friendly_name: 'Active Media Players'
      value_template: >
        {{ states.media_player
         | rejectattr('state', 'equalto', 'off')
         | rejectattr('state', 'equalto', 'idle')
         | map(attribute ='entity_id')
         | join(', ')
        }}

- platform: template
  sensors:
    day_phase:
      friendly_name: 'Day Phase'
      value_template: >
        {% if now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=9).replace(minute=0).replace(second=0) %}
            Morning
        {% elif states.sun.sun.state == "above_horizon" %}
            Day
        {% elif now() < now().replace(hour=22).replace(minute=0).replace(second=0) and
            now() > now().replace(hour=9).replace(minute=0).replace(second=0) %}
            Evening
        {% else %}
            Night
        {% endif %}
