- platform: lyft
  client_id: !secret lyft_client_id
  client_secret: !secret lyft_client_secret
  start_latitude: !secret start_latitude
  start_longitude: !secret start_longitude
  end_latitude: !secret riverfront_lat
  end_longitude: !secret riverfront_long

- platform: uber
  server_token: !secret uber_server_token
  start_latitude: !secret latitude
  start_longitude: !secret longitude
  end_latitude: !secret riverfront_lat
  end_longitude: !secret riverfront_long
  product_ids:
    - 'd755a8c4-cba2-485e-9d2a-a489d35d0182'
    - '1a150e95-d687-454b-9878-2942a9448693'
    - '653e6788-871e-4c63-a018-d04423f5b2f7'
