#####SPEED TESTS#############
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
- platform: fastdotcom
#############################

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: swap_use_percent
    - type: processor_use
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0

- platform: command_line
  name: RPI CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: command_line
  name: RPI Uptime
  command: "uptime -p | sed 's/^..//g'"

- platform: command_line
  name: HASS Uptime
  command: /home/homeassistant/.homeassistant/scripts/hass_uptime.sh

- platform: cpuspeed

- platform: version

- platform: pi_hole
  host: !secret pihole_host
  ssl: true

- platform: cert_expiry
  host: !secret hass_url
  name: cert_expire_hass

- platform: cert_expiry
  host: !secret pihole_host
  name: cert_expire_pihole

