#### GOOGLE TRAVEL TIMES ####
- platform: google_travel_time
  api_key: !secret google_drive_time_api_key
  origin: !secret home_address
  destination: !secret brad_work_address
  name: !secret brad_work_name

- platform: google_travel_time
  api_key: !secret google_drive_time_api_key
  origin: !secret home_address
  destination: !secret nat_work_address
  name: !secret nat_work_name

- platform: google_travel_time
  api_key: !secret google_drive_time_api_key
  origin: !secret brad_work_address
  destination: !secret home_address
  name: time_to_home_brad

- platform: google_travel_time
  api_key: !secret google_drive_time_api_key
  origin: !secret nat_work_address
  destination: !secret home_address
  name: time_to_home_nat
#######################################

######### UBER and LYFT ###########
- platform: lyft
  entity_namespace: lyft_to_riverfront
  scan_interval: 300
  client_id: !secret lyft_client_id
  client_secret: !secret lyft_client_secret
  start_latitude: !secret home_latitude
  start_longitude: !secret home_longitude
  end_latitude: !secret riverfront_lat
  end_longitude: !secret riverfront_long
  product_ids:
    - 'lyft'
    - 'lyft_plus'
    - 'lyft_lux_suv'

- platform: lyft
  entity_namespace: lyft_to_mike_heather
  scan_interval: 300
  client_id: !secret lyft_client_id
  client_secret: !secret lyft_client_secret
  start_latitude: !secret home_latitude
  start_longitude: !secret home_longitude
  end_latitude: !secret mike_heather_lat
  end_longitude: !secret mike_heather_long
  product_ids:
    - 'lyft'
    - 'lyft_plus'
    - 'lyft_lux_suv'

- platform: uber
  entity_namespace: uber_to_riverfront
  scan_interval: 300
  server_token: !secret uber_server_token
  start_latitude: !secret home_latitude
  start_longitude: !secret home_longitude
  end_latitude: !secret riverfront_lat
  end_longitude: !secret riverfront_long
  product_ids:
# UberXL
    - 'd755a8c4-cba2-485e-9d2a-a489d35d0182'
# UberX
    - '1a150e95-d687-454b-9878-2942a9448693'
# UberSUV
    - '653e6788-871e-4c63-a018-d04423f5b2f7'

- platform: uber
  entity_namespace: uber_to_mike_heather
  scan_interval: 300
  server_token: !secret uber_server_token
  start_latitude: !secret home_latitude
  start_longitude: !secret home_longitude
  end_latitude: !secret mike_heather_lat
  end_longitude: !secret mike_heather_long
  product_ids:
# UberXL
    - 'd755a8c4-cba2-485e-9d2a-a489d35d0182'
# UberX
    - '1a150e95-d687-454b-9878-2942a9448693'
# UberSUV
    - '653e6788-871e-4c63-a018-d04423f5b2f7'
############################################
