- platform: google_travel_time
  api_key: !secret google_drive_time_api_key
  origin: !secret home_address
  destination: !secret brad_work_address
  name: !secret brad_work_name

- platform: google_travel_time
  api_key: !secret google_drive_time_api_key
  origin: !secret home_address
  destination: !secret nat_work_address
  name: !secret nat_work_name


